return
{ { rule = { class = "Skype" },
    properties = { tag = 3,
      screen = "primary" } },
  { rule = { class = "Firefox" },
    properties = { tag = 2,
      screen = "primary" } },
  { rule = { class = "Pcmanfm" },
    properties = { tag = 4,
      screen = "primary" } },
  { rule = { class = "sublime_text" },
    properties = { tag = 1,
      screen = "primary" } },
  { rule = { class = "jetbrains-rubymine" },
    properties = { tag = 1,
      screen = "primary" } },
  { rule = { class = "Steam" },
    properties = { tag = 6,
      screen = "primary" } },
  { rule = { class = "Odeskteam-qt4" },
    properties = { tag = 5,
      screen = "primary" } },
  { rule = { class = "Gnome-system-monitor" },
    properties = { tag = 6,
      screen = "primary" } },
  { rule = { class = "urxvt" },
    properties = {  } },
  { rule = { class = "Evince" },
    properties = { tag = 4,
      screen = "primary" } },
  { rule = { class = "Transmission-gtk" },
    properties = { tag = 6,
      screen = "primary" } },
  { rule = { class = "Vlc" },
    properties = { tag = 5,
      screen = "secondary" } },
  { rule = { class = "Chromium" },
    properties = {  } },
  { rule = { class = "Pavucontrol" },
    properties = { tag = 6,
      screen = "primary" } },
  { rule = { class = "Soffice" },
    properties = { tag = 4,
      screen = "primary" } },
  { rule = { class = "jetbrains-idea" },
    properties = { tag = 1,
      screen = "primary" } },
  { rule = { class = "Hexcells Infinite.x86" },
    properties = { tag = 6,
      screen = "primary" } },
  { rule = { class = "URxvt" },
    properties = {  } },
  { rule = { class = "Hubstaff" },
    properties = { tag = 1,
      screen = "secondary" } },
  { rule = { class = "chromium" },
    properties = { tag = 2,
      screen = "primary" } },
  { rule = { class = "jetbrains-idea-c" },
    properties = { tag = 1,
      screen = "primary" } } }
