return
{ { properties = { screen = "primary",
      tag = 3 },
    rule = { class = "Skype" } },
  { properties = { screen = "primary",
      tag = 2 },
    rule = { class = "Firefox" } },
  { properties = { screen = "primary",
      tag = 4 },
    rule = { class = "Pcmanfm" } },
  { properties = { screen = "primary",
      tag = 1 },
    rule = { class = "sublime_text" } },
  { properties = { screen = "primary",
      tag = 1 },
    rule = { class = "jetbrains-rubymine" } },
  { properties = { screen = "primary",
      tag = 6 },
    rule = { class = "Steam" } },
  { properties = { screen = "primary",
      tag = 5 },
    rule = { class = "Odeskteam-qt4" } },
  { properties = { screen = "primary",
      tag = 6 },
    rule = { class = "Gnome-system-monitor" } },
  { properties = {  },
    rule = { class = "urxvt" } },
  { properties = { screen = "primary",
      tag = 4 },
    rule = { class = "Evince" } },
  { properties = { screen = "primary",
      tag = 6 },
    rule = { class = "Transmission-gtk" } },
  { properties = {  },
    rule = { class = "Vlc" } },
  { properties = {  },
    rule = { class = "Chromium" } },
  { properties = { screen = "primary",
      tag = 6 },
    rule = { class = "Pavucontrol" } },
  { properties = { screen = "primary",
      tag = 4 },
    rule = { class = "Soffice" } },
  { properties = { screen = "primary",
      tag = 1 },
    rule = { class = "jetbrains-idea" } },
  { properties = { screen = "primary",
      tag = 6 },
    rule = { class = "Hexcells Infinite.x86" } },
  { properties = {  },
    rule = { class = "URxvt" } },
  { properties = { screen = "primary",
      tag = 1 },
    rule = { class = "Hubstaff" } },
  { properties = { screen = "primary",
      tag = 2 },
    rule = { class = "chromium" } },
  { properties = { screen = "primary",
      tag = 1 },
    rule = { class = "jetbrains-idea-c" } },
  { properties = { screen = "primary",
      tag = 3 },
    rule = { class = "Slack" } },
  { properties = { screen = "primary",
      tag = 3 },
    rule = { class = "ViberPC" } },
  { properties = { screen = "primary",
      tag = 4 },
    rule = { class = "OpenOffice 4.1.2" } } }
